
allow_remote_control yes
adjust_line_height  110%
background_opacity 0.95
cursor_trail 200
enable_audio_bell no
font_family      monospace
font_size 12.0
hide_window_decorations no
initial_window_height 27c
initial_window_width  101c
tab_activity_symbol 🔔
tab_bar_edge top
tab_bar_style powerline
window_logo_alpha 0.1
window_logo_path ~/Pictures/penguin-painted-small.png
window_logo_position bottom-right
window_padding_width 2
